import { z } from "zod";

import { Product, type ProductType } from "./product.js";
import { RelatedEvent, type RelatedEventType } from "./related_event.js";
import { Remediation, type RemediationType } from "./remediation.js";

/**
 * The Finding object describes metadata related to a security finding generated by a security tool or system.
 *
 * OCSF Object: Finding
 */
export interface FindingType {
  /** The time when the finding was created. */
  created_time?: number | undefined;
  /** The description of the reported finding. */
  desc?: string | undefined;
  /** The time when the finding was first observed. */
  first_seen_time?: number | undefined;
  /** The time when the finding was most recently observed. */
  last_seen_time?: number | undefined;
  /** The time when the finding was last modified. */
  modified_time?: number | undefined;
  /** Details about the product that reported the finding. */
  product?: ProductType | undefined;
  /** The unique identifier of the product that reported the finding. */
  product_uid?: string | undefined;
  /** Describes events and/or other findings related to the finding as identified by the security product. Note that these events may or may not be in OCSF. */
  related_events?: RelatedEventType[] | undefined;
  /** Describes the recommended remediation steps to address identified issue(s). */
  remediation?: RemediationType | undefined;
  /** The URL pointing to the source of the finding. */
  src_url?: string | undefined;
  /** Additional data supporting a finding as provided by security tool */
  supporting_data?: Record<string, unknown> | undefined;
  /** A title or a brief phrase summarizing the reported finding. */
  title: string;
  /** One or more types of the reported finding. */
  types?: string[] | undefined;
  /** The unique identifier of the reported finding. */
  uid: string;
  [key: string]: unknown;
}

export const Finding: z.ZodType<FindingType> = z
  .object({
    /** The time when the finding was created. */
    created_time: z.number().int().optional(),
    /** The description of the reported finding. */
    desc: z.string().optional(),
    /** The time when the finding was first observed. */
    first_seen_time: z.number().int().optional(),
    /** The time when the finding was most recently observed. */
    last_seen_time: z.number().int().optional(),
    /** The time when the finding was last modified. */
    modified_time: z.number().int().optional(),
    /** Details about the product that reported the finding. */
    product: Product.optional(),
    /** The unique identifier of the product that reported the finding. */
    product_uid: z.string().optional(),
    /** Describes events and/or other findings related to the finding as identified by the security product. Note that these events may or may not be in OCSF. */
    related_events: z.array(RelatedEvent).optional(),
    /** Describes the recommended remediation steps to address identified issue(s). */
    remediation: Remediation.optional(),
    /** The URL pointing to the source of the finding. */
    src_url: z.string().optional(),
    /** Additional data supporting a finding as provided by security tool */
    supporting_data: z.record(z.unknown()).optional(),
    /** A title or a brief phrase summarizing the reported finding. */
    title: z.string(),
    /** One or more types of the reported finding. */
    types: z.array(z.string()).optional(),
    /** The unique identifier of the reported finding. */
    uid: z.string(),
  })
  .passthrough() as any;
