import { z } from "zod";

import { Analytic, type AnalyticType } from "./analytic.js";
import { Attack, type AttackType } from "./attack.js";
import { KeyValueObject, type KeyValueObjectType } from "./key_value_object.js";
import { KillChainPhase, type KillChainPhaseType } from "./kill_chain_phase.js";
import { Product, type ProductType } from "./product.js";
import { RelatedEvent, type RelatedEventType } from "./related_event.js";
import { Trait, type TraitType } from "./trait.js";

/**
 * The Finding Information object describes metadata related to a security finding generated by a security tool or system.
 *
 * OCSF Object: Finding Information
 */
export interface FindingInfoType {
  /** The analytic technique used to analyze and derive insights from the data or information that led to the finding or conclusion. */
  analytic?: AnalyticType | undefined;
  /** The MITRE ATT&CK® technique and associated tactics related to the finding. */
  attacks?: AttackType[] | undefined;
  /** The time when the finding was created. */
  created_time?: number | undefined;
  /** A list of data sources utilized in generation of the finding. */
  data_sources?: string[] | undefined;
  /** The description of the reported finding. */
  desc?: string | undefined;
  /** The time when the finding was first observed. e.g. The time when a vulnerability was first observed. It can differ from the created_time timestamp, which reflects the time this finding was created. */
  first_seen_time?: number | undefined;
  /** The Cyber Kill Chain® provides a detailed description of each phase and its associated activities within the broader context of a cyber attack. */
  kill_chain?: KillChainPhaseType[] | undefined;
  /** The time when the finding was most recently observed. e.g. The time when a vulnerability was most recently observed. It can differ from the modified_time timestamp, which reflects the time this finding was last modified. */
  last_seen_time?: number | undefined;
  /** The time when the finding was last modified. */
  modified_time?: number | undefined;
  /** Details about the product that reported the finding. */
  product?: ProductType | undefined;
  /** The unique identifier of the product that reported the finding. */
  product_uid?: string | undefined;
  /** Other analytics related to this finding. */
  related_analytics?: AnalyticType[] | undefined;
  /** Describes events and/or other findings related to the finding as identified by the security product. Note that these events may or may not be in OCSF. */
  related_events?: RelatedEventType[] | undefined;
  /** Number of related events or findings. */
  related_events_count?: number | undefined;
  /** The URL pointing to the source of the finding. */
  src_url?: string | undefined;
  /** The list of tags; {key:value} pairs associated with the finding. */
  tags?: KeyValueObjectType[] | undefined;
  /** A title or a brief phrase summarizing the reported finding. */
  title?: string | undefined;
  /** The list of key traits or characteristics extracted from the finding. */
  traits?: TraitType[] | undefined;
  /** One or more types of the reported finding. */
  types?: string[] | undefined;
  /** The unique identifier of the reported finding. */
  uid: string;
  /** The alternative unique identifier of the reported finding. */
  uid_alt?: string | undefined;
  [key: string]: unknown;
}

export const FindingInfo: z.ZodType<FindingInfoType> = z
  .object({
    /** The analytic technique used to analyze and derive insights from the data or information that led to the finding or conclusion. */
    analytic: z.lazy(() => Analytic).optional(),
    /** The MITRE ATT&CK® technique and associated tactics related to the finding. */
    attacks: z.array(Attack).optional(),
    /** The time when the finding was created. */
    created_time: z.number().int().optional(),
    /** A list of data sources utilized in generation of the finding. */
    data_sources: z.array(z.string()).optional(),
    /** The description of the reported finding. */
    desc: z.string().optional(),
    /** The time when the finding was first observed. e.g. The time when a vulnerability was first observed. It can differ from the created_time timestamp, which reflects the time this finding was created. */
    first_seen_time: z.number().int().optional(),
    /** The Cyber Kill Chain® provides a detailed description of each phase and its associated activities within the broader context of a cyber attack. */
    kill_chain: z.array(KillChainPhase).optional(),
    /** The time when the finding was most recently observed. e.g. The time when a vulnerability was most recently observed. It can differ from the modified_time timestamp, which reflects the time this finding was last modified. */
    last_seen_time: z.number().int().optional(),
    /** The time when the finding was last modified. */
    modified_time: z.number().int().optional(),
    /** Details about the product that reported the finding. */
    product: Product.optional(),
    /** The unique identifier of the product that reported the finding. */
    product_uid: z.string().optional(),
    /** Other analytics related to this finding. */
    related_analytics: z.array(z.lazy(() => Analytic)).optional(),
    /** Describes events and/or other findings related to the finding as identified by the security product. Note that these events may or may not be in OCSF. */
    related_events: z.array(RelatedEvent).optional(),
    /** Number of related events or findings. */
    related_events_count: z.number().int().optional(),
    /** The URL pointing to the source of the finding. */
    src_url: z.string().optional(),
    /** The list of tags; {key:value} pairs associated with the finding. */
    tags: z.array(KeyValueObject).optional(),
    /** A title or a brief phrase summarizing the reported finding. */
    title: z.string().optional(),
    /** The list of key traits or characteristics extracted from the finding. */
    traits: z.array(Trait).optional(),
    /** One or more types of the reported finding. */
    types: z.array(z.string()).optional(),
    /** The unique identifier of the reported finding. */
    uid: z.string(),
    /** The alternative unique identifier of the reported finding. */
    uid_alt: z.string().optional(),
  })
  .passthrough() as any;
