import { z } from 'zod';
import { reconcileSiblings, type SiblingPair } from '../../sibling.js';
import { prefillUids, type UidConfig } from '../../uid.js';

import { Enrichment } from '../objects/enrichment.js';
import { Metadata } from '../objects/metadata.js';
import { Observable } from '../objects/observable.js';
import { Fingerprint } from '../objects/fingerprint.js';
import { OcsfObject } from '../objects/object.js';
import { Actor } from '../objects/actor.js';
import { HttpRequest } from '../objects/http_request.js';
import { HttpResponse } from '../objects/http_response.js';
import { NetworkEndpoint } from '../objects/network_endpoint.js';
import { AuthFactor } from '../objects/auth_factor.js';
import { AuthenticationToken } from '../objects/authentication_token.js';
import { Certificate } from '../objects/certificate.js';
import { Process } from '../objects/process.js';
import { Service } from '../objects/service.js';
import { Session } from '../objects/session.js';
import { User } from '../objects/user.js';

const ACTIVITY_ID_LABELS: Record<number, string> = {
  1: "Logon",
  2: "Logoff",
  3: "Authentication Ticket",
  4: "Service Ticket Request",
  5: "Service Ticket Renew",
  6: "Preauth",
  7: "Account Switch",
};

const SEVERITY_ID_LABELS: Record<number, string> = {
  0: "Unknown",
  1: "Informational",
  2: "Low",
  3: "Medium",
  4: "High",
  5: "Critical",
  6: "Fatal",
  99: "Other",
};

const STATUS_ID_LABELS: Record<number, string> = {
  0: "Unknown",
  1: "Success",
  2: "Failure",
  99: "Other",
};

const ACCOUNT_SWITCH_TYPE_ID_LABELS: Record<number, string> = {
  0: "Unknown",
  1: "Substitute User",
  2: "Impersonate",
  99: "Other",
};

const AUTH_PROTOCOL_ID_LABELS: Record<number, string> = {
  0: "Unknown",
  1: "NTLM",
  2: "Kerberos",
  3: "Digest",
  4: "OpenID",
  5: "SAML",
  6: "OAUTH 2.0",
  7: "PAP",
  8: "CHAP",
  9: "EAP",
  10: "RADIUS",
  11: "Basic Authentication",
  12: "LDAP",
  99: "Other",
};

const LOGON_TYPE_ID_LABELS: Record<number, string> = {
  0: "Unknown",
  1: "System",
  2: "Interactive",
  3: "Network",
  4: "Batch",
  5: "OS Service",
  7: "Unlock",
  8: "Network Cleartext",
  9: "New Credentials",
  10: "Remote Interactive",
  11: "Cached Interactive",
  12: "Cached Remote Interactive",
  13: "Cached Unlock",
  99: "Other",
};

const SIBLING_PAIRS: readonly SiblingPair[] = [
  { idField: "activity_id", labelField: "activity_name", labels: ACTIVITY_ID_LABELS },
  { idField: "severity_id", labelField: "severity", labels: SEVERITY_ID_LABELS },
  { idField: "status_id", labelField: "status", labels: STATUS_ID_LABELS },
  { idField: "account_switch_type_id", labelField: "account_switch_type", labels: ACCOUNT_SWITCH_TYPE_ID_LABELS },
  { idField: "auth_protocol_id", labelField: "auth_protocol", labels: AUTH_PROTOCOL_ID_LABELS },
  { idField: "logon_type_id", labelField: "logon_type", labels: LOGON_TYPE_ID_LABELS },
];

const UID_CONFIG: UidConfig = {
  categoryUid: 3,
  classUid: 3002,
};

/**
 * Authentication events report authentication session activities, including user attempts to log on or log off, regardless of success, as well as other key stages within the authentication process. These events are typically generated by authentication services, such as Kerberos, OIDC, or SAML, and may include information about the user, the authentication method used, and the status of the authentication attempt.
 *
 * OCSF Class UID: 3002
 * Category: Authentication
 * @see https://schema.ocsf.io/1.6.0/classes/authentication
 */
export const Authentication: any = z.preprocess(
  (data) => {
    if (typeof data !== 'object' || data === null) return data;
    let d = { ...data } as Record<string, unknown>;
    d = reconcileSiblings(d, SIBLING_PAIRS);
    d = prefillUids(d, UID_CONFIG);
    return d;
  },
  z.object({
    /** The normalized identifier of the activity that triggered the event. */
    activity_id: z.number().int().optional(),
    /** The event activity name, as defined by the activity_id. */
    activity_name: z.string().optional(),
    /** The event category name, as defined by category_uid value. */
    category_name: z.string().optional(),
    /** The category unique identifier of the event. */
    category_uid: z.number().int(),
    /** The event class name, as defined by class_uid value. */
    class_name: z.string().optional(),
    /** The unique identifier of a class. A class describes the attributes available in an event. */
    class_uid: z.number().int(),
    /** The number of times that events in the same logical group occurred during the event Start Time to End Time period. */
    count: z.number().int().optional(),
    /** The event duration or aggregate time, the amount of time the event covers from start_time to end_time in milliseconds. */
    duration: z.number().int().optional(),
    /** The end time of a time period, or the time of the most recent event included in the aggregate event. */
    end_time: z.number().int().optional(),
    /** The additional information from an external data source, which is associated with the event or a finding. For example add location information for the IP address in the DNS answers:[{"name": "answers.ip", "value": "92.24.47.250", "type": "location", "data": {"city": "Socotra", "continent": "Asia", "coordinates": [-25.4153, 17.0743], "country": "YE", "desc": "Yemen"}}] */
    enrichments: z.array(Enrichment).optional(),
    /** The description of the event/finding, as defined by the source. */
    message: z.string().optional(),
    /** The metadata associated with the event or a finding. */
    metadata: Metadata,
    /** The observables associated with the event or a finding. */
    observables: z.array(Observable).optional(),
    /** The raw event/finding data as received from the source. */
    raw_data: z.string().optional(),
    /** The hash, which describes the content of the raw_data field. */
    raw_data_hash: Fingerprint.optional(),
    /** The size of the raw data which was transformed into an OCSF event, in bytes. */
    raw_data_size: z.number().int().optional(),
    /** The event/finding severity, normalized to the caption of the severity_id value. In the case of 'Other', it is defined by the source. */
    severity: z.string().optional(),
    /** The normalized identifier of the event/finding severity.The normalized severity is a measurement the effort and expense required to manage and resolve an event or incident. Smaller numerical values represent lower impact events, and larger numerical values represent higher impact events. */
    severity_id: z.number().int(),
    /** The start time of a time period, or the time of the least recent event included in the aggregate event. */
    start_time: z.number().int().optional(),
    /** The event status, normalized to the caption of the status_id value. In the case of 'Other', it is defined by the event source. */
    status: z.string().optional(),
    /** The event status code, as reported by the event source.For example, in a Windows Failed Authentication event, this would be the value of 'Failure Code', e.g. 0x18. */
    status_code: z.string().optional(),
    /** The details about the authentication request. For example, possible details for Windows logon or logoff events are:SuccessLOGOFF_USER_INITIATEDLOGOFF_OTHERFailureUSER_DOES_NOT_EXISTINVALID_CREDENTIALSACCOUNT_DISABLEDACCOUNT_LOCKED_OUTPASSWORD_EXPIRED */
    status_detail: z.string().optional(),
    /** The normalized identifier of the event status. */
    status_id: z.number().int().optional(),
    /** The normalized event occurrence time or the finding creation time. */
    time: z.number().int(),
    /** The number of minutes that the reported event time is ahead or behind UTC, in the range -1,080 to +1,080. */
    timezone_offset: z.number().int().optional(),
    /** The event/finding type name, as defined by the type_uid. */
    type_name: z.string().optional(),
    /** The event/finding type ID. It identifies the event's semantics and structure. The value is calculated by the logging system as: class_uid * 100 + activity_id. */
    type_uid: z.number().int(),
    /** The attributes that are not mapped to the event schema. The names and values of those attributes are specific to the event source. */
    unmapped: OcsfObject.optional(),
    /** The actor object describes details about the user/role/process that was the source of the activity. Note that this is not the threat actor of a campaign but may be part of a campaign. */
    actor: Actor.optional(),
    /** Details about the underlying HTTP request. */
    http_request: HttpRequest.optional(),
    /** Details about the underlying HTTP response. */
    http_response: HttpResponse.optional(),
    /** Details about the source of the IAM activity. */
    src_endpoint: NetworkEndpoint.optional(),
    /** The account switch method, normalized to the caption of the account_switch_type_id value. In the case of 'Other', it is defined by the event source. */
    account_switch_type: z.string().optional(),
    /** The normalized identifier of the account switch method. */
    account_switch_type_id: z.number().int().optional(),
    /** Describes a category of methods used for identity verification in an authentication attempt. */
    auth_factors: z.array(AuthFactor).optional(),
    /** The authentication protocol as defined by the caption of auth_protocol_id. In the case of Other, it is defined by the event source. */
    auth_protocol: z.string().optional(),
    /** The normalized identifier of the authentication protocol used to create the user session. */
    auth_protocol_id: z.number().int().optional(),
    /** The authentication token, ticket, or assertion, e.g. Kerberos, OIDC, SAML. */
    authentication_token: AuthenticationToken.optional(),
    /** The certificate associated with the authentication or pre-authentication (Kerberos). */
    certificate: Certificate.optional(),
    /** The endpoint to which the authentication was targeted. */
    dst_endpoint: NetworkEndpoint.optional(),
    /** Indicates whether the credentials were passed in clear text.Note: True if the credentials were passed in a clear text protocol such as FTP or TELNET, or if Windows detected that a user's logon password was passed to the authentication package in clear text. */
    is_cleartext: z.boolean().optional(),
    /** Indicates whether Multi Factor Authentication was used during authentication. */
    is_mfa: z.boolean().optional(),
    /** Indicates logon is from a device not seen before or a first time account logon. */
    is_new_logon: z.boolean().optional(),
    /** The attempted authentication is over a remote connection. */
    is_remote: z.boolean().optional(),
    /** The trusted process that validated the authentication credentials. */
    logon_process: Process.optional(),
    /** The logon type, normalized to the caption of the logon_type_id value. In the case of 'Other', it is defined by the event source. */
    logon_type: z.string().optional(),
    /** The normalized logon type identifier. */
    logon_type_id: z.number().int().optional(),
    /** The service or gateway to which the user or process is being authenticated */
    service: Service.optional(),
    /** The authenticated user or service session. */
    session: Session.optional(),
    /** The subject (user/role or account) to authenticate. */
    user: User,
  }).passthrough(),
);

export type AuthenticationType = z.infer<typeof Authentication>;
