import { z } from 'zod';

import type { AnalyticType } from './analytic.js';
import type { GraphType } from './graph.js';
import type { AttackType } from './attack.js';
import type { KillChainPhaseType } from './kill_chain_phase.js';
import type { ProductType } from './product.js';
import type { RelatedEventType } from './related_event.js';
import type { KeyValueObjectType } from './key_value_object.js';
import type { TraitType } from './trait.js';

/**
 * The Finding Information object describes metadata related to a security finding generated by a security tool or system.
 *
 * OCSF Object: Finding Information
 */
export interface FindingInfoType {
  /** The analytic technique used to analyze and derive insights from the data or information that led to the finding or conclusion. */
  analytic?: AnalyticType;
  /** An Attack Graph describes possible routes an attacker could take through an environment. It describes relationships between resources and their findings, such as malware detections, vulnerabilities, misconfigurations, and other security actions. */
  attack_graph?: GraphType;
  /** The MITRE ATT&CK® technique and associated tactics related to the finding. */
  attacks?: AttackType[];
  /** The time when the finding was created. */
  created_time?: number;
  /** A list of data sources utilized in generation of the finding. */
  data_sources?: string[];
  /** The description of the reported finding. */
  desc?: string;
  /** The time when the finding was first observed. e.g. The time when a vulnerability was first observed. It can differ from the created_time timestamp, which reflects the time this finding was created. */
  first_seen_time?: number;
  /** The Cyber Kill Chain® provides a detailed description of each phase and its associated activities within the broader context of a cyber attack. */
  kill_chain?: KillChainPhaseType[];
  /** The time when the finding was most recently observed. e.g. The time when a vulnerability was most recently observed. It can differ from the modified_time timestamp, which reflects the time this finding was last modified. */
  last_seen_time?: number;
  /** The time when the finding was last modified. */
  modified_time?: number;
  /** Details about the product that reported the finding. */
  product?: ProductType;
  /** The unique identifier of the product that reported the finding. */
  product_uid?: string;
  /** Other analytics related to this finding. */
  related_analytics?: AnalyticType[];
  /** Describes events and/or other findings related to the finding as identified by the security product. Note that these events may or may not be in OCSF. */
  related_events?: RelatedEventType[];
  /** Number of related events or findings. */
  related_events_count?: number;
  /** The URL pointing to the source of the finding. */
  src_url?: string;
  /** The list of tags; {key:value} pairs associated with the finding. */
  tags?: KeyValueObjectType[];
  /** A title or a brief phrase summarizing the reported finding. */
  title?: string;
  /** The list of key traits or characteristics extracted from the finding. */
  traits?: TraitType[];
  /** One or more types of the reported finding. */
  types?: string[];
  /** The unique identifier of the reported finding. */
  uid: string;
  /** The alternative unique identifier of the reported finding. */
  uid_alt?: string;
}

import { Analytic } from './analytic.js';
import { Graph } from './graph.js';
import { Attack } from './attack.js';
import { KillChainPhase } from './kill_chain_phase.js';
import { Product } from './product.js';
import { RelatedEvent } from './related_event.js';
import { KeyValueObject } from './key_value_object.js';
import { Trait } from './trait.js';

const FindingInfoSchema: z.ZodType<FindingInfoType> = z.strictObject({
  /** The analytic technique used to analyze and derive insights from the data or information that led to the finding or conclusion. */
  analytic: Analytic.optional(),
  /** An Attack Graph describes possible routes an attacker could take through an environment. It describes relationships between resources and their findings, such as malware detections, vulnerabilities, misconfigurations, and other security actions. */
  attack_graph: Graph.optional(),
  /** The MITRE ATT&CK® technique and associated tactics related to the finding. */
  attacks: z.array(Attack).optional(),
  /** The time when the finding was created. */
  created_time: z.number().int().optional(),
  /** A list of data sources utilized in generation of the finding. */
  data_sources: z.array(z.string()).optional(),
  /** The description of the reported finding. */
  desc: z.string().optional(),
  /** The time when the finding was first observed. e.g. The time when a vulnerability was first observed. It can differ from the created_time timestamp, which reflects the time this finding was created. */
  first_seen_time: z.number().int().optional(),
  /** The Cyber Kill Chain® provides a detailed description of each phase and its associated activities within the broader context of a cyber attack. */
  kill_chain: z.array(KillChainPhase).optional(),
  /** The time when the finding was most recently observed. e.g. The time when a vulnerability was most recently observed. It can differ from the modified_time timestamp, which reflects the time this finding was last modified. */
  last_seen_time: z.number().int().optional(),
  /** The time when the finding was last modified. */
  modified_time: z.number().int().optional(),
  /** Details about the product that reported the finding. */
  product: Product.optional(),
  /** The unique identifier of the product that reported the finding. */
  product_uid: z.string().optional(),
  /** Other analytics related to this finding. */
  related_analytics: z.array(Analytic).optional(),
  /** Describes events and/or other findings related to the finding as identified by the security product. Note that these events may or may not be in OCSF. */
  related_events: z.array(RelatedEvent).optional(),
  /** Number of related events or findings. */
  related_events_count: z.number().int().optional(),
  /** The URL pointing to the source of the finding. */
  src_url: z.string().optional(),
  /** The list of tags; {key:value} pairs associated with the finding. */
  tags: z.array(KeyValueObject).optional(),
  /** A title or a brief phrase summarizing the reported finding. */
  title: z.string().optional(),
  /** The list of key traits or characteristics extracted from the finding. */
  traits: z.array(Trait).optional(),
  /** One or more types of the reported finding. */
  types: z.array(z.string()).optional(),
  /** The unique identifier of the reported finding. */
  uid: z.string(),
  /** The alternative unique identifier of the reported finding. */
  uid_alt: z.string().optional(),
});

export const FindingInfo = FindingInfoSchema;
