import { z } from 'zod';

import type { ProductType } from './product.js';
import type { RelatedEventType } from './related_event.js';
import type { RemediationType } from './remediation.js';

/**
 * The Finding object describes metadata related to a security finding generated by a security tool or system.
 *
 * OCSF Object: Finding
 */
export interface FindingType {
  /** The time when the finding was created. */
  created_time?: number;
  /** The description of the reported finding. */
  desc?: string;
  /** The time when the finding was first observed. */
  first_seen_time?: number;
  /** The time when the finding was most recently observed. */
  last_seen_time?: number;
  /** The time when the finding was last modified. */
  modified_time?: number;
  /** Details about the product that reported the finding. */
  product?: ProductType;
  /** The unique identifier of the product that reported the finding. */
  product_uid?: string;
  /** Describes events and/or other findings related to the finding as identified by the security product. Note that these events may or may not be in OCSF. */
  related_events?: RelatedEventType[];
  /** Describes the recommended remediation steps to address identified issue(s). */
  remediation?: RemediationType;
  /** The URL pointing to the source of the finding. */
  src_url?: string;
  /** Additional data supporting a finding as provided by security tool */
  supporting_data?: Record<string, unknown>;
  /** A title or a brief phrase summarizing the reported finding. */
  title: string;
  /** One or more types of the reported finding. */
  types?: string[];
  /** The unique identifier of the reported finding. */
  uid: string;
}

import { Product } from './product.js';
import { RelatedEvent } from './related_event.js';
import { Remediation } from './remediation.js';

const FindingSchema = z.strictObject({
  /** The time when the finding was created. */
  created_time: z.number().int().optional(),
  /** The description of the reported finding. */
  desc: z.string().optional(),
  /** The time when the finding was first observed. */
  first_seen_time: z.number().int().optional(),
  /** The time when the finding was most recently observed. */
  last_seen_time: z.number().int().optional(),
  /** The time when the finding was last modified. */
  modified_time: z.number().int().optional(),
  /** Details about the product that reported the finding. */
  product: Product.optional(),
  /** The unique identifier of the product that reported the finding. */
  product_uid: z.string().optional(),
  /** Describes events and/or other findings related to the finding as identified by the security product. Note that these events may or may not be in OCSF. */
  related_events: z.array(RelatedEvent).optional(),
  /** Describes the recommended remediation steps to address identified issue(s). */
  remediation: Remediation.optional(),
  /** The URL pointing to the source of the finding. */
  src_url: z.string().optional(),
  /** Additional data supporting a finding as provided by security tool */
  supporting_data: z.record(z.string(), z.unknown()).optional(),
  /** A title or a brief phrase summarizing the reported finding. */
  title: z.string(),
  /** One or more types of the reported finding. */
  types: z.array(z.string()).optional(),
  /** The unique identifier of the reported finding. */
  uid: z.string(),
});

export const Finding = FindingSchema;
