import { z } from 'zod';

import { Product } from './product.js';
import { RelatedEvent } from './related_event.js';
import { Remediation } from './remediation.js';

/**
 * The Finding object describes metadata related to a security finding generated by a security tool or system.
 *
 * OCSF Object: Finding
 */
export const Finding: any = z.object({
  /** The time when the finding was created. */
  created_time: z.number().int().optional(),
  /** The description of the reported finding. */
  desc: z.string().optional(),
  /** The time when the finding was first observed. */
  first_seen_time: z.number().int().optional(),
  /** The time when the finding was most recently observed. */
  last_seen_time: z.number().int().optional(),
  /** The time when the finding was last modified. */
  modified_time: z.number().int().optional(),
  /** Details about the product that reported the finding. */
  product: Product.optional(),
  /** The unique identifier of the product that reported the finding. */
  product_uid: z.string().optional(),
  /** Describes events and/or other findings related to the finding as identified by the security product. Note that these events may or may not be in OCSF. */
  related_events: z.array(RelatedEvent).optional(),
  /** Describes the recommended remediation steps to address identified issue(s). */
  remediation: Remediation.optional(),
  /** The URL pointing to the source of the finding. */
  src_url: z.string().optional(),
  /** Additional data supporting a finding as provided by security tool */
  supporting_data: z.record(z.unknown()).optional(),
  /** A title or a brief phrase summarizing the reported finding. */
  title: z.string(),
  /** One or more types of the reported finding. */
  types: z.array(z.string()).optional(),
  /** The unique identifier of the reported finding. */
  uid: z.string(),
}).passthrough();

export type FindingType = z.infer<typeof Finding>;
