/** Observable Type ID values. */
export const ObservableTypeId = {
  UNKNOWN: 0,
  HOSTNAME: 1,
  IP_ADDRESS: 2,
  MAC_ADDRESS: 3,
  USER_NAME: 4,
  EMAIL_ADDRESS: 5,
  URL_STRING: 6,
  FILE_NAME: 7,
  HASH: 8,
  PROCESS_NAME: 9,
  RESOURCE_UID: 10,
  PORT: 11,
  SUBNET: 12,
  COMMAND_LINE: 13,
  COUNTRY: 14,
  PROCESS_ID: 15,
  HTTP_USER_AGENT: 16,
  CWE_ID: 17,
  CVE_ID: 18,
  USER_CREDENTIAL_ID: 19,
  ENDPOINT: 20,
  USER: 21,
  EMAIL: 22,
  UNIFORM_RESOURCE_LOCATOR: 23,
  FILE: 24,
  PROCESS: 25,
  GEO_LOCATION: 26,
  CONTAINER: 27,
  FINGERPRINT: 30,
  USER_UID: 31,
  GROUP_NAME: 32,
  GROUP_UID: 33,
  ACCOUNT_NAME: 34,
  ACCOUNT_UID: 35,
  SCRIPT_CONTENT: 36,
  SERIAL_NUMBER: 37,
  RESOURCE_DETAILS_NAME: 38,
  PROCESS_ENTITY_UID: 39,
  SUBJECT: 40,
  EMAIL_THREAD_UID: 41,
  MESSAGE_UID: 42,
  ADVISORY_ID: 44,
  FILE_PATH: 45,
  OTHER: 99,
} as const;

export type ObservableTypeId = (typeof ObservableTypeId)[keyof typeof ObservableTypeId];

/** Label mapping for ObservableTypeId values. */
export const ObservableTypeIdLabels: Record<number, string> = {
  0: "Unknown",
  1: "Hostname",
  2: "IP Address",
  3: "MAC Address",
  4: "User Name",
  5: "Email Address",
  6: "URL String",
  7: "File Name",
  8: "Hash",
  9: "Process Name",
  10: "Resource UID",
  11: "Port",
  12: "Subnet",
  13: "Command Line",
  14: "Country",
  15: "Process ID",
  16: "HTTP User-Agent",
  17: "CWE ID",
  18: "CVE ID",
  19: "User Credential ID",
  20: "Endpoint",
  21: "User",
  22: "Email",
  23: "Uniform Resource Locator",
  24: "File",
  25: "Process",
  26: "Geo Location",
  27: "Container",
  30: "Fingerprint",
  31: "User uid",
  32: "Group name",
  33: "Group uid",
  34: "Account name",
  35: "Account uid",
  36: "Script Content",
  37: "Serial Number",
  38: "Resource Details name",
  39: "Process Entity uid",
  40: "Subject",
  41: "Email Thread UID",
  42: "Message UID",
  44: "Advisory ID",
  45: "File Path",
  99: "Other",
};
